---
  - name: copy FRR daemons
    copy: src=config-files/{{scenario}}/{{ansible_hostname}}/daemons dest=/etc/frr/
  - name: copy FRR.conf
    copy: src=config-files/{{scenario}}/{{ansible_hostname}}/frr.conf dest=/etc/frr/

